installTraefik: true
gatewayClassName: traefik
traefikPorts:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443
image:
  repository: base-agent-system
  tag: 0.1.0
  pullPolicy: IfNotPresent
gateway:
  hostname: ""
  listenerName: web
  port: 8000
  sharedGateway:
    create: false
    namespace: traefik
    name: traefik-gateway
