apiVersion: v1
kind: Secret
metadata:
  name: base-agent-system-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secret.openaiApiKey | quote }}
  ANTHROPIC_API_KEY: {{ .Values.secret.anthropicApiKey | quote }}
  BASE_AGENT_SYSTEM_FIRECRAWL_API_KEY: {{ .Values.secret.firecrawlApiKey | quote }}
  OPIK_API_KEY: {{ .Values.secret.opikApiKey | quote }}
  BASE_AGENT_SYSTEM_POSTGRES_URI: {{ .Values.secret.postgresUri | quote }}
  BASE_AGENT_SYSTEM_NEO4J_USER: {{ .Values.secret.neo4jUser | quote }}
  BASE_AGENT_SYSTEM_NEO4J_PASSWORD: {{ .Values.secret.neo4jPassword | quote }}
